import WASM from '../../wasm.js';
const clWASM = new WASM(require('./wasm/ease.wasm'));

export default {
    InSine: clWASM.wasm.in_sine,
    OutSine: clWASM.wasm.out_sine,
    InOutSine: clWASM.wasm.in_out_sine,
    InQuad: clWASM.wasm.in_quad,
    OutQuad: clWASM.wasm.out_quad,
    InOutQuad: clWASM.wasm.in_out_quad,
    InCubic: clWASM.wasm.in_cubic,
    OutCubic: clWASM.wasm.out_cubic,
    InOutCubic: clWASM.wasm.in_out_cubic,
    InQuart: clWASM.wasm.in_quart,
    OutQuart: clWASM.wasm.out_quart,
    InOutQuart: clWASM.wasm.in_out_quart,
    InQuint: clWASM.wasm.in_quint,
    OutQuint: clWASM.wasm.out_quint,
    InOutQuint: clWASM.wasm.in_out_quint,
    InExpo: clWASM.wasm.in_expo,
    OutExpo: clWASM.wasm.out_expo,
    InOutExpo: clWASM.wasm.in_out_expo,
    InCirc: clWASM.wasm.in_circ,
    OutCirc: clWASM.wasm.out_circ,
    InOutCirc: clWASM.wasm.in_out_circ,
    InBack: clWASM.wasm.in_back,
    OutBack: clWASM.wasm.out_back,
    InOutBack: clWASM.wasm.in_out_back,
    InElastic: clWASM.wasm.in_elastic,
    OutElastic: clWASM.wasm.out_elastic,
    InOutElastic: clWASM.wasm.in_out_elastic,
    InBounce: clWASM.wasm.in_bounce,
    OutBounce: clWASM.wasm.out_bounce,
    InOutBounce: clWASM.wasm.in_out_bounce
};