declare module "*.png";
declare module "*.jpg";
declare module "*.jpeg";
declare module "*.svg";
declare module "*.mp3";
declare module "*.gif";
declare module "*.wav";
declare module "*.wasm";
declare module "*.webp";